use_frameworks!

platform :ios, '9.0'

target 'PercentageKit_Example' do
  pod 'PercentageKit', :path => '../'
  pod 'RxSwift', '~> 6.0'
  pod 'RxCocoa', '~> 6.0'
  
  target 'PercentageKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 8.0.7'
  end
end
